version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  teamcity_server_data: {}
  teamcity_server_logs: {}

services:
  postgres:
    build: 
      context: ./postgres
      args:
       database: teamcity
       user:     teamcity
       pass:     teamcity

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups

    restart: always

  teamcity-server:
    build: 
      context: ./server
      args:
        database: teamcity
        user:     teamcity
        pass:     teamcity

    volumes:
      - teamcity_server_data:/data/teamcity_server/datadir
      - teamcity_server_logs:/opt/teamcity/logs
    ports:
      - 8111:8111
    depends_on:
      - postgres
    restart: always